rename_columns = {
    "Group by Brand": {
        "BRAND": "Sales by Brand",
        "SERVICE REVENUE CURRENT": "Service Revenue Current",
        "RETAIL REVENUE CURRENT": "Retail Revenue Current",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "STORE COUNT CURRENT": "Store Count Current",
        "SERVICE REVENUE PREVIOUS": "Service Revenue Previous",
        "RETAIL REVENUE PREVIOUS": "Retail Revenue Previous",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "STORE COUNT PREVIOUS": "Store Count Previous",
        "SERVICE BUDGET": "Service Budget",
        "RETAIL BUDGET": "Retail Budget",
        "TOTAL BUDGET": "Total Budget",
        "% TOTAL BUDGET": "% Total Budget",
        "SERVICES CURRENT TO PREVIOUS %": "Services Current to Previous %",
        "RETAIL CURRENT TO PREVIOUS %": "Retail Current to Previous %",
        "TOTAL CURRENT TO PREVIOUS %": "Total Current to Previous %",
        "SERVICES REVENUE TO BUDGET %": "Services Revenue to Budget %",
        "RETAIL REVENUE TO BUDGET %": "Retail Revenue to Budget %",
        "TOTAL REVENUE TO BUDGET %": "Revenue to Budget %"
    },
    "Group by Region": {
        "REGION": "Sales by Region",
        "SERVICE REVENUE CURRENT": "Service Revenue Current",
        "RETAIL REVENUE CURRENT": "Retail Revenue Current",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "STORE COUNT CURRENT": "Store Count Current",
        "SERVICE REVENUE PREVIOUS": "Service Revenue Previous",
        "RETAIL REVENUE PREVIOUS": "Retail Revenue Previous",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "STORE COUNT PREVIOUS": "Store Count Previous",
        "SERVICE BUDGET": "Service Budget",
        "RETAIL BUDGET": "Retail Budget",
        "TOTAL BUDGET": "Total Budget",
        "% TOTAL BUDGET": "% Total Budget",
        "SERVICES CURRENT TO PREVIOUS %": "Services Current to Previous %",
        "RETAIL CURRENT TO PREVIOUS %": "Retail Current to Previous %",
        "TOTAL CURRENT TO PREVIOUS %": "Total Current to Previous %",
        "SERVICES REVENUE TO BUDGET %": "Services Revenue to Budget %",
        "RETAIL REVENUE TO BUDGET %": "Retail Revenue to Budget %",
        "TOTAL REVENUE TO BUDGET %": "Revenue to Budget %"
    },
    "Group by Category": {
        "CATEGORY": "Sales by Category",
        "SERVICE REVENUE CURRENT": "Service Revenue Current",
        "RETAIL REVENUE CURRENT": "Retail Revenue Current",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "STORE COUNT CURRENT": "Store Count Current",
        "SERVICE REVENUE PREVIOUS": "Service Revenue Previous",
        "RETAIL REVENUE PREVIOUS": "Retail Revenue Previous",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "STORE COUNT PREVIOUS": "Store Count Previous",
        "SERVICE BUDGET": "Service Budget",
        "RETAIL BUDGET": "Retail Budget",
        "TOTAL BUDGET": "Total Budget",
        "% TOTAL BUDGET": "% Total Budget",
        "SERVICES CURRENT TO PREVIOUS %": "Services Current to Previous %",
        "RETAIL CURRENT TO PREVIOUS %": "Retail Current to Previous %",
        "TOTAL CURRENT TO PREVIOUS %": "Total Current to Previous %",
        "SERVICES REVENUE TO BUDGET %": "Services Revenue to Budget %",
        "RETAIL REVENUE TO BUDGET %": "Retail Revenue to Budget %",
        "TOTAL REVENUE TO BUDGET %": "Revenue to Budget %"
    },
    "Top 10 Stores - Current Sales": {
        "CENTER": "Sales by Top 10 Stores",
        "SERVICE REVENUE CURRENT": "Service Revenue Current",
        "RETAIL REVENUE CURRENT": "Retail Revenue Current",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "SERVICE REVENUE PREVIOUS": "Service Revenue Previous",
        "RETAIL REVENUE PREVIOUS": "Retail Revenue Previous",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "SERVICE BUDGET": "Service Budget",
        "RETAIL BUDGET": "Retail Budget",
        "TOTAL BUDGET": "Total Budget",
        "% TOTAL BUDGET": "% Total Budget",
        "SERVICES CURRENT TO PREVIOUS %": "Services Current to Previous %",
        "RETAIL CURRENT TO PREVIOUS %": "Retail Current to Previous %",
        "TOTAL CURRENT TO PREVIOUS %": "Total Current to Previous %",
        "SERVICES REVENUE TO BUDGET %": "Services Revenue to Budget %",
        "RETAIL REVENUE TO BUDGET %": "Retail Revenue to Budget %",
        "TOTAL REVENUE TO BUDGET %": "Revenue to Budget %"
    },
    "ICU Stores - Current Sales": {
        "CENTER": "Sales by ICU Stores",
        "SERVICE REVENUE CURRENT": "Service Revenue Current",
        "RETAIL REVENUE CURRENT": "Retail Revenue Current",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "SERVICE REVENUE PREVIOUS": "Service Revenue Previous",
        "RETAIL REVENUE PREVIOUS": "Retail Revenue Previous",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "SERVICE BUDGET": "Service Budget",
        "RETAIL BUDGET": "Retail Budget",
        "TOTAL BUDGET": "Total Budget",
        "% TOTAL BUDGET": "% Total Budget",
        "SERVICES CURRENT TO PREVIOUS %": "Services Current to Previous %",
        "RETAIL CURRENT TO PREVIOUS %": "Retail Current to Previous %",
        "TOTAL CURRENT TO PREVIOUS %": "Total Current to Previous %",
        "SERVICES REVENUE TO BUDGET %": "Services Revenue to Budget %",
        "RETAIL REVENUE TO BUDGET %": "Retail Revenue to Budget %",
        "TOTAL REVENUE TO BUDGET %": "Revenue to Budget %"
    },
    "New Stores - Current Sales": {
        "CENTER": "Sales by New Stores",
        "SERVICE REVENUE CURRENT": "Service Revenue Current",
        "RETAIL REVENUE CURRENT": "Retail Revenue Current",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "SERVICE REVENUE PREVIOUS": "Service Revenue Previous",
        "RETAIL REVENUE PREVIOUS": "Retail Revenue Previous",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "SERVICE BUDGET": "Service Budget",
        "RETAIL BUDGET": "Retail Budget",
        "TOTAL BUDGET": "Total Budget",
        "% TOTAL BUDGET": "% Total Budget",
        "SERVICES CURRENT TO PREVIOUS %": "Services Current to Previous %",
        "RETAIL CURRENT TO PREVIOUS %": "Retail Current to Previous %",
        "TOTAL CURRENT TO PREVIOUS %": "Total Current to Previous %",
        "SERVICES REVENUE TO BUDGET %": "Services Revenue to Budget %",
        "RETAIL REVENUE TO BUDGET %": "Retail Revenue to Budget %",
        "TOTAL REVENUE TO BUDGET %": "Revenue to Budget %"
    },
    "Closed Stores - Current Sales": {
        "CENTER": "Sales by Closed Stores",
        "SERVICE REVENUE CURRENT": "Service Revenue Current",
        "RETAIL REVENUE CURRENT": "Retail Revenue Current",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "SERVICE REVENUE PREVIOUS": "Service Revenue Previous",
        "RETAIL REVENUE PREVIOUS": "Retail Revenue Previous",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "SERVICE BUDGET": "Service Budget",
        "RETAIL BUDGET": "Retail Budget",
        "TOTAL BUDGET": "Total Budget",
        "% TOTAL BUDGET": "% Total Budget",
        "SERVICES CURRENT TO PREVIOUS %": "Services Current to Previous %",
        "RETAIL CURRENT TO PREVIOUS %": "Retail Current to Previous %",
        "TOTAL CURRENT TO PREVIOUS %": "Total Current to Previous %",
        "SERVICES REVENUE TO BUDGET %": "Services Revenue to Budget %",
        "RETAIL REVENUE TO BUDGET %": "Retail Revenue to Budget %",
        "TOTAL REVENUE TO BUDGET %": "Revenue to Budget %"
    },
    "Top 20 Service Items": {
        "CATEGORY": "Service Top 20",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "TOTAL UNITS CURRENT": "Total Units Current",
        "TOTAL UNITS PREVIOUS": "Total Units Previous",
        "STORE COUNT CURRENT": "Store Count Current",
        "STORE COUNT PREVIOUS": "Store Count Previous",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "% CURRENT UNITS CONTR": "% Current Units Contr",
        "% PREVIOUS UNITS CONTR": "% Previous Units Contr",
        "RAND CURRENT TO PREVIOUS %": "Rand Current to Previous %",
        "UNITS CURRENT TO PREVIOUS%": "Units Current to Previous %",
        "AVERAGE REVENUE GROWTH PER STORE %": "Average Revenue Growth Per Store %"
    },
    "Total Lines Service": {
        "TOTAL REVENUE CURRENT": "Group Revenue Current",
        "TOTAL REVENUE PREVIOUS": "Group Revenue Previous",
        "TOTAL UNITS CURRENT": "Group Total Units Current",
        "TOTAL UNITS PREVIOUS": "Group Total Units Previous",
        "TOP 20 CURRENT REVENUE OVER TOTAL %": "Top 20 Current Revenue Over Total %",
        "TOP 20 PREVIOUS REVENUE OVER TOTAL %": "Top 20 Previous Revenue Over Total %",
        "TOP 20 CURRENT UNITS OVER TOTAL %": "Top 20 Current Units Over Total %",
        "TOP 20 PREVIOUS UNITS OVER TOTAL %": "Top 20 Previous Units Over Total %"
    
    },
    "Bottom 10 Service Items": {
        "CATEGORY": "Service Bottom 10",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "TOTAL UNITS CURRENT": "Total Units Current",
        "TOTAL UNITS PREVIOUS": "Total Units Previous",
        "STORE COUNT CURRENT": "Store Count Current",
        "STORE COUNT PREVIOUS": "Store Count Previous",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "% CURRENT UNITS CONTR": "% Current Units Contr",
        "% PREVIOUS UNITS CONTR": "% Previous Units Contr",
        "RAND CURRENT TO PREVIOUS %": "Rand Current to Previous %",
        "UNITS CURRENT TO PREVIOUS%": "Units Current to Previous %",
        "AVERAGE REVENUE GROWTH PER STORE %": "Average Revenue Growth Per Store %"
    },
    "Top 20 Retail Items": {
        "CATEGORY": "Retail Top 20",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "TOTAL UNITS CURRENT": "Total Units Current",
        "TOTAL UNITS PREVIOUS": "Total Units Previous",
        "STORE COUNT CURRENT": "Store Count Current",
        "STORE COUNT PREVIOUS": "Store Count Previous",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "% CURRENT UNITS CONTR": "% Current Units Contr",
        "% PREVIOUS UNITS CONTR": "% Previous Units Contr",
        "RAND CURRENT TO PREVIOUS %": "Rand Current to Previous %",
        "UNITS CURRENT TO PREVIOUS%": "Units Current to Previous %",
        "AVERAGE REVENUE GROWTH PER STORE %": "Average Revenue Growth Per Store %"
    },
    "Total Lines Retail": {
        "TOTAL REVENUE CURRENT": "Group Revenue Current",
        "TOTAL REVENUE PREVIOUS": "Group Revenue Previous",
        "TOTAL UNITS CURRENT": "Group Total Units Current",
        "TOTAL UNITS PREVIOUS": "Group Total Units Previous",
        "TOP 20 CURRENT REVENUE OVER TOTAL %": "Top 20 Current Revenue Over Total %",
        "TOP 20 PREVIOUS REVENUE OVER TOTAL %": "Top 20 Previous Revenue Over Total %",
        "TOP 20 CURRENT UNITS OVER TOTAL %": "Top 20 Current Units Over Total %",
        "TOP 20 PREVIOUS UNITS OVER TOTAL %": "Top 20 Previous Units Over Total %"
    },
    "Bottom 10 Retail Items": {
        "CATEGORY": "Retail Bottom 10",
        "TOTAL REVENUE CURRENT": "Total Revenue Current",
        "TOTAL REVENUE PREVIOUS": "Total Revenue Previous",
        "TOTAL UNITS CURRENT": "Total Units Current",
        "TOTAL UNITS PREVIOUS": "Total Units Previous",
        "STORE COUNT CURRENT": "Store Count Current",
        "STORE COUNT PREVIOUS": "Store Count Previous",
        "% CURRENT REV CONTR": "% Current Rev Contr",
        "% PREVIOUS REV CONTR": "% Previous Rev Contr",
        "% CURRENT UNITS CONTR": "% Current Units Contr",
        "% PREVIOUS UNITS CONTR": "% Previous Units Contr",
        "RAND CURRENT TO PREVIOUS %": "Rand Current to Previous %",
        "UNITS CURRENT TO PREVIOUS%": "Units Current to Previous %",
        "AVERAGE REVENUE GROWTH PER STORE %": "Average Revenue Growth Per Store %"
    },
    "Loyalty KPI": {
        "Metric_Type": "Loyalty KPI",
        "Green": "Green",
        "Blue": "Blue",
        "Silver": "Silver",
        "Gold": "Gold",
        "Total Loyalty": "Total Loyalty",
        "Non-loyalty": "Non-loyalty",
        "Total": "Total"
    },
    "Ops KPI - Group by Region": {
        "Metric_Type": "Sales Key Metrics - Group by Region",
        "Inland": "Inland",
        "KwaZulu-Natal": "KwaZulu-Natal",
        "Western Cape": "Western Cape",
        "TOTAL": "Group"
    },
    "Ops KPI - Group by Category": {
        "Metric_Type": "Sales Key Metrics - Group by Category",
        "A +": "A +",
        "A": "A",
        "B": "B",
        "C": "C",
        "TOTAL": "Group"
    },
    "Ops KPI - Group by Brand": {
        "Metric_Type": "Sales Key Metrics - Group by Brand",
        "Candi & Co": "Candi & Co",
        "Hybrid": "Hybrid",
        "Sorbet Hairbar": "Sorbet Hairbar",
        "Sorbet Man": "Sorbet Man",
        "Sorbet Man Hybrid": "Sorbet Man Hybrid",
        "Sorbet Nails": "Sorbet Nails",
        "Sorbet Salon": "Sorbet Salon",
        "TOTAL": "Group"
    },
    "Clicks Loyalty KPI": {
        "Metric_Type": "Clicks vs Non clicks",
        "CURRENT": "Current",
        "PREVIOUS": "Previous",
        "GROWTH": "Growth"
    },
    "Clicks Loyalty KPI Top 20 Centers": {
        "CENTER": "Top 20 Contributing Stores",
        "CLICKS_TO_TOTAL_SALES": "Clicks to Total Sales %",
        "CLICKS_BASKET_SIZE_TO_NON_CLICKS_BASKET_SIZE": "Clicks Basket Size % Non Clicks Basket Size",
        "NEW_GUEST_TO_UNIQUE_GUEST": "New Guest to Unique Guest %",
        "NEW_CLICKS_LOYALTY_GUEST_TO_UNIQUE_GUESTS": "New Clicks Loyalty Guest to Unique Guests %"
    },
    "Clicks Loyalty KPI Bottom 20 Centers": {
        "CENTER": "Bottom 20 Contributing Stores",
        "CLICKS_TO_TOTAL_SALES": "Clicks to Total Sales %",
        "CLICKS_BASKET_SIZE_TO_NON_CLICKS_BASKET_SIZE": "Clicks Basket Size % Non Clicks Basket Size",
        "NEW_GUEST_TO_UNIQUE_GUEST": "New Guest to Unique Guest %",
        "NEW_CLICKS_LOYALTY_GUEST_TO_UNIQUE_GUESTS": "New Clicks Loyalty Guest to Unique Guests %"
    }
}
